### ISSUE TITLE
proof_pietrzak Iterations

### ISSUE THREAD

**Issue by 0xmountaintop** [poanetwork/vdf#20]
May I ask why in https://github.com/poanetwork/vdf/blob/master/vdf/src/proof_pietrzak.rs#L45-L58

the iteration number has to be even and >=66?  I couldn't find evidence for it in:
+ https://eprint.iacr.org/2018/627.pdf
+ https://eprint.iacr.org/2018/712.pdf

**Comment by jose-compu** [comment]
Good question.

**Comment by 0xmountaintop** [comment]
We've figured it out.

---

> the iteration number has to be even

https://eprint.iacr.org/2018/627.pdf 's idea is to keep halving, so the teration number has to be even

---

> the iteration number has to be >=66

+ delta is 8 by defalut.
    + https://github.com/poanetwork/vdf/blob/c740ef3b9a4b4663b672ada93bb1c9ba0c80a965/vdf/src/proof_pietrzak.rs#L169
+ in `generate_proof`, when `calculate_final_t`, the last _delta_ elements will be removed from the !Vec[.... 64, 32, 16, 8, 4, 2, 1], so iterations > 64
    + https://github.com/poanetwork/vdf/blob/c740ef3b9a4b4663b672ada93bb1c9ba0c80a965/vdf/src/proof_pietrzak.rs#L242

---

## about delta 
this is related to an optimization technique discussed in https://eprint.iacr.org/2018/627.pdf. 
See section 6.2 _Efficiency of the VDF_'s _A minor efficiency improvement_
